<?php
/**
 *  2Moons 
 *   by Jan-Otto Kröpke 2009-2016
 *
 * For the full copyright and license information, please view the LICENSE
 *
 * @package 2Moons
 * @author Jan-Otto Kröpke <slaver7@gmail.com>
 * @copyright 2009 Lucky
 * @copyright 2016 Jan-Otto Kröpke <slaver7@gmail.com>
 * @licence MIT
 * @version 1.8.0
 * @link https://github.com/jkroepke/2Moons
 */
// Translated into English by QwataKayean . All rights reversed (C) 2012
// 2Moons - Copyright (C) 2010-2012 Slaver
$LNG['faq_overview']	= "FAQ";
 
$LNG['questions']					= array();
$LNG['questions'][1]['category']	= 'Tips for Beginners';
$LNG['questions'][1][1]['title']	= 'Step 1 - Your First Buildings';
$LNG['questions'][1][1]['body']		= <<<BODY
<p>This part of the tutorial describes the main buildings in the game.</p>
<h3>Solar Power Plant:</h3>
<p>The Solar Plant generates energy, which is used to produce the three main resources. For this production to actually occur, the energy used in production cannot exceed the energy generated by the plant. When the load exceeds the available energy, energy numbers in the menu turn red. Avoid running with an energy deficit.</p>
<h3>Ore Extractor:</h3>
<p>Metal is the first of the three main resources available in the game. It is used for almost everything you can build or research. Therefore, expansion of the ore extractors is advised.</p>
<h3>Silicon Refiner:</h3>
<p>Silicon is highly used for buildings, ships, and research. It is produced more slowly than metal, making it more expensive.</p>
<h3>Uranium Centrifuge:</h3>
<p>Uranium is a fuel source, highly used for research, as fuel for ships, and for scanning star systems.</p>
BODY;
$LNG['questions'][1][2]['title']	= 'Step 2 - Your Next Buildings';
$LNG['questions'][1][2]['body']		= <<<BODY
<p>To expand your empire and compete with other players you need to construct additional buildings.</p>
<h3>The Shipyard:</h3>
<p>After constructing a Shipyard you can begin assembling a fleet and planet defenses. Look at the Technologies tab to find the list of all available ships in the game. Some ships have higher technology requirements. Leveling up the Shipyard enables faster construction of ships and defenses.</p>
<h3>The Research Lab:</h3>
<p>Researching new technologies unlocks new buildings, ships and defenses. Technologies tab also shows the list of all available research. Research can also yield bonuses for production and combat. Research progress can be accelerated by upgrading the Research Lab building.</p>
<h3>Robot Factory:</h3>
<p>The Robot Factory is an essential building for speeding up the building construction queue. Updgrade this building to reduce construction time of buildings.</p>
BODY;
$LNG['questions'][1][3]['title']	= 'Step 3 - First Combat';
$LNG['questions'][1][3]['body']		= <<<BODY
<p>This part of the tutorial is dedicated to defending the planet and first actions with your own fleet.</p>
<h3>Galaxy:</h3>
<p>The Galaxy tab is used to find nearby planets and players. Here you will find detailed information on planets. Quick actions allow you to dispatch fleets and missiles. Besides that, you can message other players and send spy probes to collect intel.</p>
<h3>Sending Fleets:</h3>
<p>You can send your fleet directly from the Galaxy tab or from the Fleets tab. First, select which ship types quantity to send on a mission. Second, enter the coordinates (auto-filled if you clicked on the planet) and select the speed of flying. A slower flight consumes less fuel. </p>
<p>The last step is selecting which type of mission, such as Attack, Transfer, Transport, Recycle, Colonize, Expedition, or Deploy. </p>
<p>Transfer means to gift the ship to the target player. Recycle is for collecting battle debris. Colonize is only for colony ships to settle on a new planet. Expedition is available when flying to deep space for exploration.
<h3>Planetary Defense:</h3>
<p>Defenses protect your planets in addition to parked ships. These offer some protection against raiding enemy ships. Unlike fleet ships, 70% of destroyed defences are repaired after battle.</p>
BODY;
$LNG['questions'][2]['category']	= 'Step 4 - Advanced Combat';
$LNG['questions'][2][1]['title']	= 'Raid';
$LNG['questions'][2][1]['body']		= <<<BODY
<h3>Raids:</h3>
<p>A raid is an attack on another player's planet to steal resources. If an attack is successful, up to 50% of the resources on the target planet may be taken as plunder. There are several types of attacks such as</p>:
<ul>
<li>Inactive Raids</li>
<li>ACS(Alliance Combat System)</li>
<li>Intercepting a fleet</li>
</ul>
<h3>Inactive Raids:</h3>
<p>A focused raider tries to steal resources fast and easy. Often, your neighbors are all active players who are online or fleet saving. Inactive players are easier targets as they are not likely to come online.</p>
<h3>Alliance Combat System (ACS):</h3>
<p>Alliance Combat System (or ACS) allows for friends and alliance members to temporarily combine their fleets for attack or defence, to take down or repel a more powerful enemy. Building an Alliance Depot is not a pre-requisite to use ACS.</p>
<h3>Intercepting a fleet:</h3>
<p>Fleet interception is difficult. You must determine how, when and where the player is saving the fleet. To do that you have to observe the player. Using phalanx sensor, you can detect fleets on planets. Depending on how the player hides, you may have to destroy moon(s) to detect the fleets.</p>
BODY;
$LNG['questions'][2][2]['title']	= 'Fleet Save Tactics';
$LNG['questions'][2][2]['body']		= <<<BODY
<h3>Protecting ships using Fleet Save tactics:</h3>
<p>Heavy defenses can make raiders hesistate to attack ships parked at a planet. In some universes destoyed defenses do not contribute to debris field. </p>
<p>Missiles can be used to wipe out defenses, since Interplanetery Missile's only aim is to destroy defenses. Missiles are one-time use, unlike ships. A well-planned attack, with several interplanetary missiles reduces the danger of losing a fleet. Interceptor missiles are less expensive and counter the missile threat.</p>
<p>Increase of spy research level allows you to probe the planets and defenses of the other players.</p>
<p>It is best no player can see all of what you have while you are offline. Raiders can only probe and steal the resources on the planet, not cargo that is flying through space. Enemies may decide you are weak and poor and not bother to attack you.</p>
<h3>Fleet Save:</h3>
<p>Fleet Saving is a key component of the game strategy. It works by sending your fleet to a nearby planet on a Transfer Mission, checking the time so you can be online to "Return" the flight before it arrives at the destination.</p>
<p>Another way to protect the fleet is to send it to a moon or a debris field. Enemies can't use Phalanx Sensor to scan moons to find the fleet.</p>
BODY;
$LNG['questions'][2][3]['title']	= 'Moons';
$LNG['questions'][2][3]['body']		= <<<BODY
<p>A moon can form when a field of debris has at least 100,000 units, and you are lucky with a roll of dice. Default universe setting is a 1% chance for moon. Maxsimum is only 20% chance no matter how big the debris field is.</p>
<h3>General</h3>
<p>The moons can be named and the default name is "Moon". You can have more than one moon, max one per planet. </p>
<h3>Sizes of Moons</h3>
<p>A moon can be spawned depending on the number of units destroyed in combat. Destroying 1667 Light Cargos/Fighters has a 20% chance to spawn a moon. Light Cargos are recommended because they are easy to destroy.</p>
<p>The target planet should have defenses sufficient to destroy the ships. Build at least 3334 Missle Launchers or Light Laser Turrets.</p>
<p>The amount of destruction from the battle will determine the size of the moon</p>
<p>Probability for Moons between 1% and 19% is of random size and probability of 20% the moon will have 8000 km in diameter. Regular moons are never exceeding 8944 km in diameter.</p>
<h3>Construction</h3>
<p>On moons, you can build resource storage, Robot or Nanite Factory, Moonbase, Phalanx Sensor, Alliance Depot, Shipyard and Jumpgate. The Shipyard is not very useful because you can quickly transfer ships from the planet. Alliance Depot is useful for defending the Moon.</p>
<p>The three specific buildings on the moon are:</p>
<ul><li><p><b>Lunar Base</b><br>Used to create new fields, and each level adds 3 additional fields.</p></li>
<li><p><b>Phalanx Sensor</b><br>Used to view activities of enemy fleets to and from planets, but cannot scan moons. It has a limited range of galaxies, but can be upgraded to extend the range.</p></li>
<li><p><b>Jumpgates</b><br>Used to teleport a fleet from one moon to another instantaneously. It cannot be used to transfer resources.</p></li></ul>
<p>Here is a list of the ideal development of a Moon:<br>
<b>Legend:</b><br>
MB – Moon Base<br>
SP – Phalanx<br>
ST – Jumpgate<br>
RB – Robots Factory</p>
<p>MB1 – RB1 – RB2 – MB2 – SP1 – RB3 – MB3 – SP2 – RB4 – MB4 – SP3 – RB5 – MB5 – SP4 – RB6 – MB6 – SP5 – SP6 – MB7 – SP7 – SP8 – MB8 – ST1<br>
This order is only suggested if you are new, because of course an expert player has their own ideas.<p>
<h3>Destruction of Moons:</h3>
<p>Moons can be destroyed by one type of ship, called Battle Fortress.</p>
<p>In the Fleet menu, select a Battle Fortress and target a Moon, then choose Destroy for the mission type. Destroy missions are not guaranteed to succeed. The larger the moon, the more Battle Fortresses required.</p>
BODY;
$LNG['questions'][2][4]['title']	= 'Alliance';
$LNG['questions'][2][4]['body']		= <<<BODY
<h3>Forming an Alliance</h3>
<p>To form an alliance, go to the Alliance menu and select Create Alliance. Choose the short TAG of your alliance and the name.</p>
<p>To manage the alliance you will find the following links:</p>
<p>Members: see the list of all members</p>
<p>Your rank: Here find your rank in the alliance</p>
<p>Global Message: send a broadcast message to all players in the alliance</p>
<h3>Managing your Alliance:</h3>
<p>Edit the description of the alliance, edit ranks,  edit the members</p>
<p>Update external text, a brief description of your alliance for all players who visit the page of the Alliance.</p>
<p>Update internal text, exclusive content only visibile to the members of the alliance. For example current enemies, allies, target coordinates, etc.</p>
<p>Also in the settings, you can edit the image displayed on the alliance page.</p>
<p>Dissolve Alliance: is the function to delete the alliance. If you want to abandon the Alliance but do you want to delete, then instead give ownership to another player.</p>
BODY;
